### ISSUE TITLE
Broken internal links in src/tutorials/app

### ISSUE THREAD

**Issue by klehelley** [cozy/cozy.github.io#125]
In the [Cozy application tutorial page, section "Handle data with `cozy-client`](https://docs.cozy.io/en/tutorials/app/#handle-data-with-cozy-client), the two links ["User guide"](https://docs.cozy.io/en/cozy-client/guide/) and ["API docs"](https://docs.cozy.io/en/cozy-client/api/) refer to pages that do not exist.

**Comment by Crash--** [comment]
Thank you for the report! 

Should be fixed in https://github.com/cozy/cozy.github.io/pull/126

**Comment by Crash--** [comment]
It's now fixed & deployed. 

Thanks you again for this report :)
