### ISSUE TITLE
Archived documentation

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy.github.io#198]
When searching some informations about konnectors, I ended up on this page https://docs.cozy.io/en/cozy-stack/archives/konnectors-design/ 

This documentation is archived and only kept to keep track of our thoughts, but I'm not sure we need to index it or make it accessible on docs.cozy.io. 

This documentation is here since it's stored on cozy-stack/docs/archives, and cozy-stack/docs is an "outside_docs" so we ended by mapping on all its content and... serve this archives/ folder. 

What do you think the best approach is? Adding an "exclude_pattern" for "external documentation" or moving this archive folder away from cozy-stack/docs ? Other alternatives / ideas ?

**Comment by ptbrowne** [comment]
We could add an exclude pattern for external documentation, seems like a good idea.
