### ISSUE TITLE
Folders missing in french documentation

### ISSUE THREAD

**Issue by clochix** [cozy/cozy.github.io#66]
Compare https://github.com/cozy/cozy.github.io/tree/master/fr with https://github.com/cozy/cozy.github.io/tree/master/en or https://github.com/cozy/cozy.github.io/tree/dev/docs/fr Some files and folders are missing:

 - dev
 - download
 - index_fr
 - install
 - sync
 - use

**Comment by ptbrowne** [comment]
fixed in https://github.com/cozy/cozy.github.io/pull/67
