### ISSUE TITLE
Black text on black background

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy.github.io#70]
There's a problem with the code block theme:

![image](https://user-images.githubusercontent.com/701648/40552234-63806fe6-603f-11e8-981b-dfc552d9c88b.png)

**Comment by ptbrowne** [comment]
Related (from Bruno)
> la coloration syntaxique pour les requêtes HTTP est illisible sur docs.cozy.io

**Comment by ptbrowne** [comment]
fixed by https://github.com/cozy/cozy.github.io/commit/3cd460b56fe35e37ae89346567d64fdccc70baa7
