### ISSUE TITLE
Connector or Konnector ?

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy.github.io#71]
The documentation needs to be clear for external developers, and the fact that we sometimes use the word _connector_ and sometimes _konnectors_ is pretty confusing.

Personally I prefer _connector_ because it's explicit. But in the code base and for legacy reason, _konnector_ is used so to me it is more logical to keep this term.

||konnector|connector|
|-|-|-|
|Meaningful|❌|✅|
|Not ugly|❌|✅|
|Consistent with codebase|✅|❌|
|Consistent with repositories|✅|❌|

Don't forget kids, always name things the simplest way as possible, and avoid excentric spellings.

**Comment by nono** [comment]
In my mind, it's "konnector" on the developer side, and "connector" on the end user side. "Connector" will be replaced by "_App de collect_" (Collecting app?), so we should probably avoid using "connector".

**Comment by edas** [comment]
I don't know the rational for using _konnector_ initialy so don't have any strong opinion. I agree to have one unique naming but don't really care which it is unless someone does bring something new.

As I saw it, _konnector_ was just confortable for not saying _Cozy connector_, and having a specific name for our specific usage (like the way lawyers use specific terms with specific definitions when putting them in caps)

**Comment by ptbrowne** [comment]
I prefer connector in the documentation as I find the word "konnector" ugly. I think it is the term that has been chosen when communicating externally so for coherence, I would be in favor of removing konnector.

**Comment by enguerran** [comment]
Do we have a vote on which term to use?
Or is it a rational decision (not that a vote is irrational, eh :wink:) on the part of the project's referents?

My 2 cents is that creating a term for a product is very useful if and only if it is a real product. The connectors are just a set of features so they shall have a simple and easy to catch feature name like __connectors__.

**Comment by drazik** [comment]
I prefer "connector", but just because I find "konnector" is ugly. There's no marketing / technical / whatever consideration in my opinion.

**Comment by ptbrowne** [comment]
@aenario @doubleface @enguerran @sebn An opinion ?

**Comment by aenario** [comment]
History: konnector was chosen at a point were we felt our projects names `cozy-note, cozy-todo, cozy-files, cozy-proxy` where boring and lacked *pétillance*, plus we wanted to separate it from the cozy brand, in the hope to create a emulation (more people makes konnector, other personal cloud projects use them, ect...)

This plan failed, so now **Connector** is the proper term in all user-facing text and should be kept that way. However, all the code (in collect, stack, konnector-libs, github orga) uses **konnector** , which makes it easier to search all and is too extensive to change now. 

Contributor are more than users, so let's just be clear and explicit about it : Let's put in the external-dev documentation a line like 
> For historical reason, in the cozy codebase, a cozy connector is named `konnector`, please follow this convention if modifying an existing application.

My $.02

**Comment by sebn** [comment]
As a developer, I find the collect/connector/konnector wording confusing, whatever the level (doc, code...).
Also I wonder whether we really need a "collect app" concept: although an app may only collect data initially, isn't the goal to make it a full-fledged one in the end? What about the other way (some data collect being introduced later into an existing app)?
Will we even need a *connector* manifest?
Wouldn't it make sense to just configure jobs in manifests and have a JS(X) one-liner to show the default UI to configure some collect job?

**Comment by sebn** [comment]
Regarding the initial question: I prefer *connector* (like it sounds) to *konnector* (confusing imho, e.g.where should the k go?), and I agree it would be expensive to change it right now and we better wait for the *everything-becomes-an-app* move and keep the code consistent for now.

**Comment by ptbrowne** [comment]
Closed by https://github.com/cozy/cozy.github.io/commit/134f7ad342f228a4692343f1b1bd191ef88a9ba8
